name: Run Experiment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      COPERNICUSMARINE_SERVICE_USERNAME: ${{ secrets.COPERNICUSMARINE_SERVICE_USERNAME }}
      COPERNICUSMARINE_SERVICE_PASSWORD: ${{ secrets.COPERNICUSMARINE_SERVICE_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          environment-name: fiesta-scattering-sst
          init-shell: bash
          cache-environment: true

      - name: Setup Copernicus Marine credentials
        run: |
          mkdir -p ~/.copernicusmarine
          echo "[credentials]
          username=${COPERNICUSMARINE_SERVICE_USERNAME}
          password=${COPERNICUSMARINE_SERVICE_PASSWORD}" | base64 > ~/.copernicusmarine/.copernicusmarine-credentials

      - name: Run notebook
        shell: micromamba-shell {0}
        run: |
          jupytext --to notebook 01_sst_gap_filling.py
          jupyter execute --inplace 01_sst_gap_filling.ipynb
